version: '3.9'

services:
  springboot-app:
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/myapp
    networks:
      - spring-mongo-network
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - spring-mongo-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  spring-mongo-network:
    driver: bridge

volumes:
  mongo-data:
